@startuml shopping
[front end] as Front_end
[Login and Register] as Li
[Order] as Order
[Inquire] as Inquire
[Shopping] as Shopping
[commodity management] as Management
[database] as Database
[pay] as Pay

Front_end --( HTTPS
HTTPS -- Li
HTTPS -- Order
HTTPS -- Inquire
HTTPS -- Shopping


Shopping ..> Pay
Shopping ..> Management

Li --( SQL
Inquire --( SQL
Shopping --( SQL
Management --( SQL
Order --( SQL

Database -- SQL
Database -- SQL
Database -- SQL
@enduml